INSERT INTO Servers (Name) VALUES ('Syrio');
INSERT INTO Servers (Name) VALUES ('NewC');
INSERT INTO Servers (Name) VALUES ('AD01');
INSERT INTO Servers (Name) VALUES ('Nickel');
INSERT INTO Servers (Name) VALUES ('Zinc');
INSERT INTO Servers (Name) VALUES ('Carbon');
INSERT INTO Servers (Name) VALUES ('Cobalt');
INSERT INTO Servers (Name) VALUES ('Web02');
INSERT INTO Servers (Name) VALUES ('Projects');
INSERT INTO Servers (Name) VALUES ( 'Aphro');
INSERT INTO Servers (Name) VALUES ( 'Ada-1');
INSERT INTO Servers (Name) VALUES ( 'Ai1');
INSERT INTO Servers (Name) VALUES ( 'Ai2');
INSERT INTO Servers (Name) VALUES ( 'Cara');